# Generated by Django 3.2 on 2021-05-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210501_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
    ]
