# Generated by Django 3.2 on 2021-05-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_brand_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
    ]
