# Generated by Django 3.2 on 2021-05-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_brand_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSecondary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
