# Generated by Django 3.2 on 2021-05-09 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_brandsecondary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrandSecondary',
        ),
    ]
